version: '3.4'

services:
  socca.footballclub.api:
    image: ${DOCKER_REGISTRY-}soccafootballclub
    build:
      context: .
      dockerfile: src/Microservices/FootballClub/Api/Socca.FootballClub.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "62245:80"
      - "44301:443"
#    depends_on: 
#      - db

  socca.footballclubstadium.api:
    image: ${DOCKER_REGISTRY-}soccafootballclubstadium
    build:
      context: .
      dockerfile: src/Microservices/FootballClubStadium/Api/Socca.FootballClubStadium.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "63784:80"
      - "44350:443"
#    depends_on: 
#      - db

  socca.players.api:
    image: ${DOCKER_REGISTRY-}soccaplayers
    build:
      context: .
      dockerfile: src/Microservices/Players/Api/Socca.Players.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "19578:80"
      - "44328:443"
#    depends_on: 
#      - db

  socca.stadium.api:
    image: ${DOCKER_REGISTRY-}soccastadium
    build:
      context: .
      dockerfile: src/Microservices/Stadium/Api/Socca.Stadium.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "3094:80"
      - "44309:443"
#    depends_on: 
#      - db

  socca.playertransfers.api:
    image: ${DOCKER_REGISTRY-}soccaplayertransfers
    build:
      context: .
      dockerfile: src/Microservices/PlayerTransfers/Api/Socca.PlayerTransfers.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "16956:80"
      - "44370:443"
#    depends_on: 
#      - db

  socca.distributedcache.api:
    image: ${DOCKER_REGISTRY-}soccadistributedcache
    build:
      context: .
      dockerfile: src/Microservices/DistributedCache/Api/Socca.DistributedCache.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "14417:80"
      - "44305:443"

#  db:
#      image: mcr.microsoft.com/mssql/server:2019-latest
#      ports:
#          - "5434:1433"
#      environment:
#          - ACCEPT_EULA=Y
          #- MSSQL_PID=Express
#          - SA_PASSWORD=Password2021
#      expose:
#          - "1433"


networks:
  default:
    external:
      name: soccanet
