version: '3.4'

services:
  socca.footballclub.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44301
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
    ports:
      - "62245:80"
      - "44301:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on: 
      - db
      - rabbitmq

  socca.footballclubstadium.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44350
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
    ports:
      - "63784:80"
      - "44350:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on: 
      - db
      - rabbitmq

  socca.players.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44328
      #- ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword"
    ports:
      - "19578:80"
      - "44328:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on: 
      - db
      - rabbitmq

  socca.stadium.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44309
      #- ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword"
    ports:
      - "3094:80"
      - "44309:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on: 
      - db
      - rabbitmq

  socca.playertransfers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44370
      #- ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword"
    ports:
      - "16956:80"
      - "44370:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on: 
      - db
      - rabbitmq

  socca.distributedcache.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44305
      #- ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword
    ports:
      - "14417:80"
      - "44305:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on: 
      - redis_image
      - rabbitmq

  db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password2021
      ports:
        - "5434:1433"

  redis_image:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq