version: '3.4'

services:
  socca.footballclub.api:
    image: ${DOCKER_REGISTRY-}soccafootballclub
    build:
      context: .
      dockerfile: src/Microservices/FootballClub/Api/Socca.FootballClub.Api/Dockerfile

  socca.footballclubstadium.api:
    image: ${DOCKER_REGISTRY-}soccafootballclubstadium
    build:
      context: .
      dockerfile: src/Microservices/FootballClubStadium/Api/Socca.FootballClubStadium.Api/Dockerfile

  socca.players.api:
    image: ${DOCKER_REGISTRY-}soccaplayers
    build:
      context: .
      dockerfile: src/Microservices/Players/Api/Socca.Players.Api/Dockerfile

  socca.stadium.api:
    image: ${DOCKER_REGISTRY-}soccastadium
    build:
      context: .
      dockerfile: src/Microservices/Stadium/Api/Socca.Stadium.Api/Dockerfile

  socca.playertransfers.api:
    image: ${DOCKER_REGISTRY-}soccaplayertransfers
    build:
      context: .
      dockerfile: src/Microservices/PlayerTransfers/Api/Socca.PlayerTransfers.Api/Dockerfile

  socca.distributedcache.api:
    image: ${DOCKER_REGISTRY-}soccadistributedcache
    build:
      context: .
      dockerfile: src/Microservices/DistributedCache/Api/Socca.DistributedCache.Api/Dockerfile

